baseURL = ""
languageCode = "en-us"
title = "Kubewarden"
theme = "projects-theme"
pluralizeListTitles = false
enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableGitInfo = true
googleAnalytics = 'G-PSW07XK7TM'

[blackfriday]
fractions = false
#hrefTargetBlank = true

[outputFormats.Algolia]
baseName = "algolia"
isPlaintext = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

[params]
github = "https://github.com/kubewarden"

[outputs]
home = ["HTML", "RSS"]

[privacy]
[privacy.googleAnalytics]
anonymizeIP = true

[menu]

[[menu.main]]
identifier = "hub"
name = "Policies"
url = "https://artifacthub.io/packages/search?kind=13&sort=relevance&page=1"
weight = -130

[[menu.main]]
identifier = "charts"
name = "Helm Charts"
url = "https://charts.kubewarden.io/"
weight = -120

[[menu.main]]
identifier = "docs"
name = "Docs"
url = "https://docs.kubewarden.io/"
weight = -110

[[menu.main]]
identifier = "slack"
name = "Slack"
url = "https://kubernetes.slack.com/?redir=%2Fmessages%2Fkubewarden"
weight = -90

[[menu.main]]
identifier = "bluesky"
name = "Bluesky"
url = "https://bsky.app/profile/kubewarden.io"
weight = -85

[[menu.main]]
identifier = "mastodon"
name = "Mastodon"
url = "https://hachyderm.io/@kubewarden"
weight = -80
[menu.main.params]
rel = 'me'

[[menu.main]]
identifier = "community"
name = "Community"
url = "/#get-in-touch"
weight = -70

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog"
weight = -60

[[menu.main]]
identifier = "enterprise"
name = "Enterprise"
url = "https://docs.kubewarden.io/enterprise"
weight = -50
