# Configuration file to customize the build process of the website when
# previewing it on Netlify.
[build]
publish = "public"
command = "hugo --config config.toml,config-netlify.toml"

[build.environment]
HUGO_VERSION = "0.133.0"
